version: '3.7'
services:
  elasticsearch1:
    image: containerregfortestteam.azurecr.io/elasticsearch1:v1
    container_name: elasticsearch1
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: VElasticCluster
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: false
      - type: volume
        source: esdata1
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    restart: always
  logstash1:
    image: containerregfortestteam.azurecr.io/logstash1:v1
    depends_on:
      - elasticsearch1
    container_name: logstash1
    volumes:
      - type: bind
        source: ./logstash/config/
        target: /usr/share/logstash/config/
        read_only: true
      - type: bind
        source: ./logstash/pipeline/
        target: /usr/share/logstash/pipeline/
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    restart: always
  grafana:
    image: containerregfortestteam.azurecr.io/grafana1:v1
    depends_on:
      - elasticsearch1
    container_name: grafana1
    networks:
      - elk
    volumes:
      - type: bind
        source: ./grafana
        target: /var/lib/grafana
    user: "0"
    ports:
      - "3000:3000"
volumes:
  esdata1:
    driver: local
networks:
  elk:
    driver: overlay
